### ISSUE TITLE
Pls help check my hardware support anot?

### ISSUE THREAD

**Issue by kentwk** [Andrea-Fox/peopleCounter#19]
![WhatsApp Image 2021-04-10 at 11 39 08 PM](https://user-images.githubusercontent.com/55240103/114276319-ae7a9200-9a58-11eb-86c3-4449be8fc154.jpeg)
![WhatsApp Image 2021-04-10 at 11 59 25 PM](https://user-images.githubusercontent.com/55240103/114276345-d4a03200-9a58-11eb-8b28-a4a7c64fa85e.jpeg)
![WhatsApp Image 2021-04-10 at 11 59 26 PM](https://user-images.githubusercontent.com/55240103/114276350-d5d15f00-9a58-11eb-945e-cab97651c3cb.jpeg)

Pls help check my hardware support anot? Because I walk from which way result keep zero.

**Comment by Andrea-Fox** [comment]
The connections seem correct. Maybe the issue is the sensor. First of all, is it a VL53L1X sensor? If so, in general there is some sort of cover on the sensor. Try removing that.  
If then it still doesn't work, try connecting it to a 5v pin

**Comment by kentwk** [comment]
> The connections seem correct. Maybe the issue is the sensor. First of all, is it a VL53L1X sensor? If so, in general there is some sort of cover on the sensor. Try removing that.
> If then it still doesn't work, try connecting it to a 5v pin

1)Yes...is VL53L1X-V2
1)Soft cover removed
2)Tried use 5v pin...not working

Do u mind show your sensor?

**Comment by Andrea-Fox** [comment]
Then I really don't know which is the problem. 
Maybe the sensor is defective

**Comment by kentwk** [comment]
> Then I really don't know which is the problem.
> Maybe the sensor is defective

but i have tried few sensor also same...izzit u sensor same with me?if working izzit serial monitor result 0 will change 1 then 2?

**Comment by Andrea-Fox** [comment]
Currently I'm using a sensor from Pololu, which is not the one you're using.

When working, in the signal monitor you should read the distance measured by the sensor (in your case, unfortunately, always equal to 0)

**Comment by kentwk** [comment]
> Currently I'm using a sensor from Pololu, which is not the one you're using.
> 
> When working, in the signal monitor you should read the distance measured by the sensor (in your case, unfortunately, always equal to 0)

Do u mind screen shot your serial monitor?

**Comment by kentwk** [comment]
> Currently I'm using a sensor from Pololu, which is not the one you're using.
> 
> When working, in the signal monitor you should read the distance measured by the sensor (in your case, unfortunately, always equal to 0)

After soldering sensors working.TQ
i use manual_calibration can count people, when using autocalibration no working...may i noe using autocalibration what mqtt topic should i write?

**Comment by Andrea-Fox** [comment]
If you are using the code in the file called `people_counter_esp32.ino` or the one in `people_counter_esp8266.ino`, you have to subscribe to the topic `people_counter/NAME_OF_THE_ROOM/counter`, while if you want to read the distance you have to subscribe to the topic `people_counter/NAME_OF_THE_ROOM/distance`.
To specify the name of the room, you have to change the code in the line indicated in the file

**Comment by sanderlv** [comment]
same issue maybe here...
![image](https://user-images.githubusercontent.com/16528916/118698071-47e35380-b810-11eb-8fd0-fd201b05a542.png)

successfully flashed but not connecting to wifi and no serial logging in arduino IDE? I do get some on ither serial monitor
```
Using 'COM16' as serial port.
Showing logs:
[19:39:12]ets Jun  8 2016 00:22:57
[19:39:12]
[19:39:12]rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[19:39:12]configsip: 0, SPIWP:0xee
[19:39:12]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[19:39:12]mode:DIO, clock div:1
[19:39:12]load:0x3fff0018,len:4
[19:39:12]load:0x3fff001c,len:1216
[19:39:12]ho 0 tail 12 room 4
[19:39:12]load:0x40078000,len:10944
[19:39:12]load:0x40080400,len:6388
[19:39:12]entry 0x400806b4
[19:39:12]E (58) psram: PSRAM ID read error: 0xffffffff
[19:39:12][19:39:12]
[19:39:12]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[19:39:12]configsip: 0, SPIWP:0xee
[19:39:12]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[19:39:12]mode:DIO, clock div:1
[19:39:12]load:0x3fff0018,len:4
[19:39:12]load:0x3fff001c,len:1216
[19:39:12]ho 0 tail 12 room 4
[19:39:12]load:0x40078000,len:10944
[19:39:12]load:0x40080400,len:6388
[19:39:12]entry 0x400806b4
[19:39:12]E (59) psram: PSRAM ID read error: 0xffffffff
```

**Comment by kentwk** [comment]
> same issue maybe here...
> ![image](https://user-images.githubusercontent.com/16528916/118698071-47e35380-b810-11eb-8fd0-fd201b05a542.png)
> 
> successfully flashed but not connecting to wifi and no serial logging in arduino IDE? I do get some on ither serial monitor
> 
> ```
> Using 'COM16' as serial port.
> Showing logs:
> [19:39:12]ets Jun  8 2016 00:22:57
> [19:39:12]
> [19:39:12]rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> [19:39:12]configsip: 0, SPIWP:0xee
> [19:39:12]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> [19:39:12]mode:DIO, clock div:1
> [19:39:12]load:0x3fff0018,len:4
> [19:39:12]load:0x3fff001c,len:1216
> [19:39:12]ho 0 tail 12 room 4
> [19:39:12]load:0x40078000,len:10944
> [19:39:12]load:0x40080400,len:6388
> [19:39:12]entry 0x400806b4
> [19:39:12]E (58) psram: PSRAM ID read error: 0xffffffff
> [19:39:12][19:39:12]
> [19:39:12]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> [19:39:12]configsip: 0, SPIWP:0xee
> [19:39:12]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> [19:39:12]mode:DIO, clock div:1
> [19:39:12]load:0x3fff0018,len:4
> [19:39:12]load:0x3fff001c,len:1216
> [19:39:12]ho 0 tail 12 room 4
> [19:39:12]load:0x40078000,len:10944
> [19:39:12]load:0x40080400,len:6388
> [19:39:12]entry 0x400806b4
> [19:39:12]E (59) psram: PSRAM ID read error: 0xffffffff
> ```

Maybe u can check few things
1)void setup_wifi() 
{
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) 
  {
    delay(5000);
    Serial.print(".");
    WiFi.begin(ssid, password);
  }
}

***Delay from 500 change to 5000***

2)Serial monitor set 9600baud
![9600](https://user-images.githubusercontent.com/55240103/118767509-6c8f0800-b8b0-11eb-9e09-b13aa4b603ba.jpg)

**Comment by sanderlv** [comment]
Serial monitor was 9600 👍 but I can not get any output?
![image](https://user-images.githubusercontent.com/16528916/118772980-a34f2900-b884-11eb-9636-3a0ce70df489.png)

I changed the 500 to 5000 and it comes alive now... will proceed further with homeassitsant integration etc.

thanks!!

**Comment by kentwk** [comment]
Make sure to fill in correct information.

![wifi](https://user-images.githubusercontent.com/55240103/118774588-964c2d00-b8b8-11eb-855d-d5470882158d.jpg)

**Comment by sanderlv** [comment]
Yes, that is correct because I am getting mqtt information:
![image](https://user-images.githubusercontent.com/16528916/118774995-bc58d980-b886-11eb-8e17-0566d9bdb1db.png)

Oh... for my sensor orientation? Do you happen to know like below:
https://github.com/Andrea-Fox/peopleCounter/blob/master/autocalibration/sensor_orientation.png

I have a VL53L1X

**Comment by kentwk** [comment]
> Yes, that is correct because I am getting mqtt information:
> ![image](https://user-images.githubusercontent.com/16528916/118774995-bc58d980-b886-11eb-8e17-0566d9bdb1db.png)
> 
> Oh... for my sensor orientation? Do you happen to know like below:
> https://github.com/Andrea-Fox/peopleCounter/blob/master/autocalibration/sensor_orientation.png
> 
> I have a VL53L1X

no...I use the manual calibration counting people is working...if using auto calibration no working, no matter what i change MQTT topic also same.

**Comment by sanderlv** [comment]
for an ESP32 what would I have to use?

https://github.com/Andrea-Fox/peopleCounter/tree/master/manual_calibration

**Comment by kentwk** [comment]
peopleCounter.ino

**Comment by sanderlv** [comment]
Hm... that looks complicated for now. i want to try with auto first. I do not see any change on the mqtt tpoic people_counter/tof_people/counter... I do see continuous change on the people_counter/tof_people_ard/distance topic... any tips/suggestion?

**Comment by kentwk** [comment]
**Manual Calibration Setting**
1)double-check u serial monitor working anot...if same with my screenshot mean working.then u can next step
![Serial Monitor](https://user-images.githubusercontent.com/55240103/118825918-acc0ab80-b8ed-11eb-8c7c-3299aed812f2.png)

2)Go Homeassistant-Congfiguration-Helpers-Add Helper
![Helper](https://user-images.githubusercontent.com/55240103/118827593-1a210c00-b8ef-11eb-825a-01219a957178.png)

3)Go Homeassistant-Files Editor-automations.yaml-add below these script
![yaml](https://user-images.githubusercontent.com/55240103/118828090-8a2f9200-b8ef-11eb-8165-28a89e94aa05.png)

4)Done
![Done](https://user-images.githubusercontent.com/55240103/118828448-dd094980-b8ef-11eb-96c8-e43b217e4f6a.png)

**Comment by sanderlv** [comment]
Yes that works:
![image](https://user-images.githubusercontent.com/16528916/118828800-e083dd00-b8bd-11eb-9179-11ebc94960e2.png)


but no people are counting yet:
![image](https://user-images.githubusercontent.com/16528916/118828869-f1345300-b8bd-11eb-86e2-4bbc00722dd4.png)

![image](https://user-images.githubusercontent.com/16528916/118828943-00b39c00-b8be-11eb-991c-5d007649a45c.png)

![image](https://user-images.githubusercontent.com/16528916/118828998-0c06c780-b8be-11eb-8fe4-2f7ca53a06e5.png)

**Comment by kentwk** [comment]
u using manual calibration or auto calibration?

**Follow this Topic**
topic: "peopleCounter/serialdata/tx"

**Comment by sanderlv** [comment]
Auto

**Comment by kentwk** [comment]
> Auto

u try using manual...because auto calibration also no working for me.

**Comment by sanderlv** [comment]
Sorry but I have read that and I do not know how to start with that manual calibrarion

**Comment by kentwk** [comment]
> Sorry but I have read that and I do not know how to start with that manual calibrarion

just flash the manual calibration files...then follow my step.

**Comment by sanderlv** [comment]
I flashed https://github.com/Andrea-Fox/peopleCounter/blob/master/manual_calibration/peopleCounter.ino and entered my data but it wont connect to wifi and I see no serial logging...

![image](https://user-images.githubusercontent.com/16528916/118863132-d32b1a80-b8de-11eb-9b7f-ad3a2567c849.png)

And not sure what is meant with this:
![image](https://user-images.githubusercontent.com/16528916/118863456-32892a80-b8df-11eb-9ce5-fea10624d9f0.png)


I do this and get:
![image](https://user-images.githubusercontent.com/16528916/118863441-2c934980-b8df-11eb-8f67-dbe25da89f50.png)

**Comment by kentwk** [comment]
u forgot change wifi delay?

void setup_wifi()
{
WiFi.begin(ssid, password);
while (WiFi.status() != WL_CONNECTED)
{
delay(5000);
Serial.print(".");
WiFi.begin(ssid, password);
}
}

Delay from 500 change to 5000

**Comment by sanderlv** [comment]
Don't know how that happened... I did thought I checked it, but probably not well enough.. I get now:
![mqtt manual](https://user-images.githubusercontent.com/16528916/118942016-a0226e80-b952-11eb-83db-cd4c9b860cba.gif)

**Comment by Andrea-Fox** [comment]
Hi, what you are seeing in your last message is the correct behavior. The topic in `peopleCounter/serialdata` is updated only whenever a passage is detected. 
A passage is detected whenever the array of 4 numbers (the one which is in general 0000) is either 0132 or 0231

**Comment by kentwk** [comment]
Let me conclude my topic...just my soldering problem. TQ
