### ISSUE TITLE
Possible to use ESP8266 ?

### ISSUE THREAD

**Issue by Cliff-R-K** [Andrea-Fox/peopleCounter#2]
Is it possible to use an ESP8266 instead of a ESP32 or do you need the extra processing power that the ESP32 has ?

**Comment by Andrea-Fox** [comment]
In theory it should work also for the ESP8266 as all the connections needed are there, but unfortunately I've never tried it. In any case, I don't think that the processing power needed is too high to handle for the ESP8266.  
If you succeed in using it with an ESP8266, please tell me so I can update the read.me file

**Comment by Andrea-Fox** [comment]
I've added a new code specific for ESP8266 (just a slight modification of the original file). You can find it as peopleCounterESP8266.ino in the main folder
