### ISSUE TITLE
People in the room now: 111227

### ISSUE THREAD

**Issue by sotidis** [Andrea-Fox/peopleCounter#4]
Hello . is it ok?

: warning: 'RIGHT' defined but not used [-Wunused-variable]
 static int RIGHT = 1;
            ^

One person has entered in the room. People in the room now: 111227
One person has exited the room. People in the room now: 71227

**Comment by Andrea-Fox** [comment]
No, there is definitely something wrong. Later this day I will update the code to eliminate this kind of behavior, however my advice is to use this code only for finding when someone is entering (or exiting) the room and keep count of the people inside the room using, for example, Home Assistant

**Comment by sotidis** [comment]
Thanks ! i use iobroker ,if the value People in the room now: "-" 111227 ,  does not count correctly.

**Comment by Andrea-Fox** [comment]
I've edited the code and eliminated the lines of code that produced that output. Thank you for noticing that
