### ISSUE TITLE
Updated ST algorithm V2

### ISSUE THREAD

**Issue by markjones89** [Andrea-Fox/peopleCounter#6]
Hi @Andrea-Fox 

Thanks for this project, I noticed on ST's website that they have released version 2 of there code, from what I can see they have updated the code to include a buffer of measurements to feed into the counting algorithm for better accuracy. This might be of some interest for your project. 

https://www.st.com/en/embedded-software/stsw-img010.html

**Comment by Andrea-Fox** [comment]
Thank you for the suggestion! I will give a look in the future and see if I'm able to create a similar updated version also for esp32/esp8266

**Comment by itekhi** [comment]
Would love to see the V2 update :)
Do you have files of their V1 code? I could compare them to see what's new.

**Comment by Andrea-Fox** [comment]
Hi, I've added in the original_code folder their V1 code which is currently not available on their website
