### ISSUE TITLE
Esphome integration

### ISSUE THREAD

**Issue by JannickBlmndl** [Andrea-Fox/peopleCounter#8]
Do you know esphome? It has seamless integration with home assistant. I'm busy on a way to integrate the people counting people concept with the VL53L1X sensor to Esphome. Don't know if it's working this way but here's is the repo: https://github.com/DutchDeffy/esphome_custom_component_VL53L1X_people_counter.

**Comment by Andrea-Fox** [comment]
Unfortunately I discovered esphome only a few weeks after creating this project :)  
However I'm planning to integrate this idea into that project, as it is much better and would probably reach an higher number of people

**Comment by JannickBlmndl** [comment]
There’s already a pull request for adding the sensor to Esphome as a component which passsd all the checks and is to be reviewed and checked. The code doesn’t do the algorithm and people counting logic yet. Currently it does do the distance measuring part, which is already really brilliant. Maybe it could help you out. The PR is referenced by #1447 and #916 for the docs.

**Comment by Andrea-Fox** [comment]
Unfortunately integrating this code into esphome is far above my current skills. I opened an issue in the esphome request form ([#1119](https://github.com/esphome/feature-requests/issues/1119)) to see if someone else is able to do so
